import { KnowledgeEntry, BaselineItem } from './types'

export const KNOWLEDGE_BASE: KnowledgeEntry[] = [
  // Physical Health
  {
    id: 'kb-1',
    pillar: 'health',
    expert: 'Dr. Matthew Walker',
    domain: 'Sleep Science',
    directive: 'Maintain a consistent sleep-wake time within a ±30-minute window every day, including weekends, to anchor your circadian rhythm.',
    source: 'Why We Sleep — Scribner (2017)',
    sourceYear: 2017,
  },
  {
    id: 'kb-2',
    pillar: 'health',
    expert: 'Dr. Peter Attia',
    domain: 'Longevity Medicine',
    directive: 'Accumulate 150–180 minutes of Zone 2 cardio per week at a conversational pace to build aerobic base and mitochondrial density.',
    source: 'Outlive: The Science and Art of Longevity — Harmony Books (2023)',
    sourceYear: 2023,
  },
  {
    id: 'kb-3',
    pillar: 'health',
    expert: 'Dr. Andrew Huberman',
    domain: 'Circadian Biology',
    directive: 'Capture outdoor light within 30–60 minutes of waking to set cortisol pulse and anchor your circadian clock. No sunglasses during this window.',
    source: 'Huberman Lab Podcast — Episode 2: Master Your Sleep (2021)',
    sourceYear: 2021,
  },
  // Mental Health & Happiness
  {
    id: 'kb-4',
    pillar: 'mind',
    expert: 'Dr. Martin Seligman',
    domain: 'Positive Psychology (PERMA)',
    directive: 'Flourishing requires five pillars: Positive Emotion, Engagement, Relationships, Meaning, and Accomplishment. Daily attention to each compounds over time.',
    source: 'Flourish — Free Press (2011)',
    sourceYear: 2011,
  },
  {
    id: 'kb-5',
    pillar: 'mind',
    expert: 'Cal Newport',
    domain: 'Deep Work & Cognitive Performance',
    directive: 'Schedule uninterrupted deep work blocks of ≥90 minutes. Treat this like a surgery appointment — immovable, phone off, door closed.',
    source: 'Deep Work: Rules for Focused Success — Grand Central Publishing (2016)',
    sourceYear: 2016,
  },
  {
    id: 'kb-6',
    pillar: 'mind',
    expert: 'Dr. Carol Dweck',
    domain: 'Growth Mindset Psychology',
    directive: 'When encountering failure, reframe the internal narrative from "I failed" to "I have not yet mastered this." Calibrate praise toward process effort, not fixed talent.',
    source: 'Mindset: The New Psychology of Success — Random House (2006)',
    sourceYear: 2006,
  },
  // Meaning & Purpose
  {
    id: 'kb-7',
    pillar: 'purpose',
    expert: 'Dr. Viktor Frankl',
    domain: 'Logotherapy',
    directive: 'Meaning is found in what you give to the world (creation), what you receive from it (experience), and how you face unavoidable suffering (attitude). Purpose is not discovered — it is lived.',
    source: "Man's Search for Meaning — Beacon Press (1946)",
    sourceYear: 1946,
  },
  {
    id: 'kb-8',
    pillar: 'purpose',
    expert: 'James Clear',
    domain: 'Marginal Gains',
    directive: 'Pursue 1% compound improvements rather than breakthrough leaps. A 1% daily improvement compounds to 37× better over one year. The system, not the goal, determines the outcome.',
    source: 'Atomic Habits — Avery Publishing (2018)',
    sourceYear: 2018,
  },
  // Close Relationships
  {
    id: 'kb-9',
    pillar: 'relationships',
    expert: 'Dr. John Gottman',
    domain: 'Relationship Science',
    directive: 'Maintain a minimum 5:1 ratio of positive-to-negative interactions in close relationships. A single critical exchange requires five genuine positive moments to restore relational equilibrium.',
    source: 'The Seven Principles for Making Marriage Work — Crown Publishers (1999)',
    sourceYear: 1999,
  },
  {
    id: 'kb-10',
    pillar: 'relationships',
    expert: 'Robert Waldinger',
    domain: 'Harvard Study of Adult Development',
    directive: 'The quality of close relationships is the single strongest predictor of late-life happiness and health — stronger than wealth, fame, or IQ. Loneliness is as damaging as smoking 15 cigarettes a day.',
    source: 'The Good Life — Simon & Schuster (2023)',
    sourceYear: 2023,
  },
  // Financial Stability
  {
    id: 'kb-11',
    pillar: 'finance',
    expert: 'Ramit Sethi',
    domain: 'Behavioral Finance & Automation',
    directive: 'Automate 100% of savings, investments, and fixed bills. Human willpower is finite — remove financial decisions from the cognitive queue entirely through system architecture.',
    source: 'I Will Teach You to Be Rich — Workman Publishing (2019)',
    sourceYear: 2019,
  },
  {
    id: 'kb-12',
    pillar: 'finance',
    expert: 'Morgan Housel',
    domain: 'Financial Psychology',
    directive: 'Define your "enough" before optimizing any portfolio. Wealth without a defined ceiling creates a hedonic treadmill with no finish line and no satisfaction.',
    source: 'The Psychology of Money — Harriman House (2020)',
    sourceYear: 2020,
  },
  // Character & Virtue
  {
    id: 'kb-13',
    pillar: 'character',
    expert: 'Dr. Tyler VanderWeele',
    domain: 'Global Flourishing Study',
    directive: 'Character and virtue — honesty, compassion, courage, and self-control — are not merely moral ideals but empirical predictors of long-term wellbeing and social trust.',
    source: 'Flourishing: What It Is and How to Measure It — Harvard T.H. Chan School of Public Health (2017)',
    sourceYear: 2017,
  },
  {
    id: 'kb-14',
    pillar: 'character',
    expert: 'AKDN / Aga Khan Trust for Culture',
    domain: 'Contextual Development & Ethics',
    directive: 'Localize any capability-transfer initiative to its geographic, cultural, and historical context. Universal solutions applied without local calibration generate dependency, not resilience.',
    source: 'AKDN Ethical Framework — Aga Khan Development Network (2018)',
    sourceYear: 2018,
  },
  // Spiritual Wellbeing
  {
    id: 'kb-15',
    pillar: 'spirit',
    expert: 'Dr. Tyler VanderWeele',
    domain: 'Global Flourishing Study',
    directive: 'Spiritual wellbeing — a sense of connection to something larger than oneself — is a significant independent predictor of wellbeing outcomes across all cultures studied, regardless of religious affiliation.',
    source: 'Global Flourishing Study — Harvard / Gallup (2023)',
    sourceYear: 2023,
  },
]

export const DEFAULT_BASELINES: BaselineItem[] = [
  {
    id: 'bl-1',
    pillar: 'health',
    label: 'Morning light exposure',
    threshold: 'Outdoor light within 60 minutes of waking',
    reflectionPrompt: 'Did you capture morning light with intention, or were you indoors behind glass?',
    logs: [],
  },
  {
    id: 'bl-2',
    pillar: 'health',
    label: 'Consistent sleep anchor',
    threshold: 'Sleep and wake within ±30 min of target times',
    reflectionPrompt: 'Did you honor your sleep window last night, or did you negotiate with it?',
    logs: [],
  },
  {
    id: 'bl-3',
    pillar: 'mind',
    label: 'Deep work block',
    threshold: 'At least one 90-minute uninterrupted focus session',
    reflectionPrompt: 'Was your deep work block genuinely protected, or were you reachable throughout?',
    logs: [],
  },
  {
    id: 'bl-4',
    pillar: 'mind',
    label: 'Emotional check-in',
    threshold: 'A brief honest assessment of your mental state today',
    reflectionPrompt: 'How would you honestly describe your emotional state today — not how you performed, but how you were?',
    logs: [],
  },
  {
    id: 'bl-5',
    pillar: 'purpose',
    label: 'Purposeful work',
    threshold: 'At least one task today connected to your longer-term meaning',
    reflectionPrompt: 'Did anything you did today feel genuinely meaningful — not just useful or productive?',
    logs: [],
  },
  {
    id: 'bl-6',
    pillar: 'relationships',
    label: 'Undistracted presence',
    threshold: 'At least one fully present interaction with a close person',
    reflectionPrompt: 'Was your presence with someone today full and attentive, or were you physically present but mentally elsewhere?',
    logs: [],
  },
  {
    id: 'bl-7',
    pillar: 'finance',
    label: 'Automated systems running',
    threshold: 'All scheduled transfers and investments executed without manual intervention',
    reflectionPrompt: 'Did your financial system operate on its own today, or did you intervene unnecessarily?',
    logs: [],
  },
  {
    id: 'bl-8',
    pillar: 'character',
    label: 'Acted with integrity',
    threshold: 'No action taken today that contradicts your stated values',
    reflectionPrompt: 'Was there any moment today where you acted against what you believe — even in a small way?',
    logs: [],
  },
  {
    id: 'bl-9',
    pillar: 'spirit',
    label: 'Moment of transcendence',
    threshold: 'A brief moment of gratitude, awe, prayer, or connection to something larger',
    reflectionPrompt: 'Did you experience anything today that made you feel part of something beyond yourself?',
    logs: [],
  },
]
