import { KnowledgeEntry, BaselineItem, LifePillar } from './types'

export const KNOWLEDGE_BASE: KnowledgeEntry[] = [
  {
    id: 'kb-1',
    pillar: 'health',
    expert: 'Dr. Matthew Walker',
    domain: 'Sleep Science',
    directive: 'Maintain a consistent sleep-wake time within a ±30-minute window every day, including weekends, to anchor your circadian rhythm.',
    source: 'Why We Sleep — Scribner (2017)',
    sourceYear: 2017,
  },
  {
    id: 'kb-2',
    pillar: 'health',
    expert: 'Dr. Peter Attia',
    domain: 'Longevity Medicine',
    directive: 'Accumulate 150–180 minutes of Zone 2 cardio per week (conversational pace, lactate ~2 mmol/L) to build aerobic base and mitochondrial density.',
    source: 'Outlive: The Science and Art of Longevity — Harmony Books (2023)',
    sourceYear: 2023,
  },
  {
    id: 'kb-3',
    pillar: 'health',
    expert: 'Dr. Andrew Huberman',
    domain: 'Neuroscience & Circadian Biology',
    directive: 'Capture outdoor light within 30–60 minutes of waking to set cortisol pulse and anchor the circadian clock. No sunglasses during this window.',
    source: 'Huberman Lab Podcast — Episode 2: Master Your Sleep (2021)',
    sourceYear: 2021,
  },
  {
    id: 'kb-4',
    pillar: 'health',
    expert: 'Dr. Peter Attia',
    domain: 'Functional Strength',
    directive: 'Track grip strength as a proxy for longevity. Aim for a deadhang of ≥60 seconds and monitor for decline. Low grip strength is a top mortality predictor.',
    source: 'Outlive — Chapter 11: Strength (2023)',
    sourceYear: 2023,
  },
  {
    id: 'kb-5',
    pillar: 'learning',
    expert: 'Cal Newport',
    domain: 'Deep Work & Cognitive Performance',
    directive: 'Schedule uninterrupted deep work blocks of ≥90 minutes. Treat this like a surgery appointment — immovable, phone off, door closed.',
    source: 'Deep Work: Rules for Focused Success — Grand Central Publishing (2016)',
    sourceYear: 2016,
  },
  {
    id: 'kb-6',
    pillar: 'learning',
    expert: 'Dr. Carol Dweck',
    domain: 'Growth Mindset Psychology',
    directive: 'When encountering failure, reframe the internal narrative from "I failed" to "I have not yet mastered this." Calibrate praise toward process effort, not fixed talent.',
    source: 'Mindset: The New Psychology of Success — Random House (2006)',
    sourceYear: 2006,
  },
  {
    id: 'kb-7',
    pillar: 'learning',
    expert: 'Cal Newport',
    domain: 'Cognitive Load Management',
    directive: 'Apply a strict Work-in-Progress (WIP) limit of 2–3 active cognitive projects. Context switching carries a measurable cognitive tax; defend focus through structural constraints.',
    source: 'A World Without Email — Portfolio/Penguin (2021)',
    sourceYear: 2021,
  },
  {
    id: 'kb-8',
    pillar: 'finance',
    expert: 'Ramit Sethi',
    domain: 'Behavioral Finance & Automation',
    directive: 'Automate 100% of savings, investments, and fixed bills. Human willpower is finite — remove financial decisions from the cognitive queue entirely through system architecture.',
    source: 'I Will Teach You to Be Rich — Workman Publishing (2009, rev. 2019)',
    sourceYear: 2019,
  },
  {
    id: 'kb-9',
    pillar: 'finance',
    expert: 'Morgan Housel',
    domain: 'Financial Psychology',
    directive: 'Define your "Rich Life" in concrete, personal terms before optimizing any portfolio. The target must precede the strategy. Wealth without a defined purpose creates psychological instability.',
    source: 'The Psychology of Money — Harriman House (2020)',
    sourceYear: 2020,
  },
  {
    id: 'kb-10',
    pillar: 'relationships',
    expert: 'Dr. John Gottman',
    domain: 'Relationship Science',
    directive: 'Maintain a minimum 5:1 ratio of positive-to-negative interactions in close relationships. A single critical exchange requires five genuine positive moments to restore relational equilibrium.',
    source: 'The Seven Principles for Making Marriage Work — Crown Publishers (1999)',
    sourceYear: 1999,
  },
  {
    id: 'kb-11',
    pillar: 'relationships',
    expert: 'Dr. John Gottman',
    domain: 'Active Constructive Response',
    directive: 'Respond to a partner\'s good news with active and constructive engagement — ask follow-up questions, show genuine enthusiasm. Passive or destructive responses erode relational trust faster than conflict.',
    source: 'The Relationship Cure — Crown Publishers (2001)',
    sourceYear: 2001,
  },
  {
    id: 'kb-12',
    pillar: 'community',
    expert: 'Peter Singer',
    domain: 'Effective Altruism',
    directive: 'Direct charitable capital toward interventions with empirically measurable outcomes per dollar. Prioritize by cost-effectiveness per life-year saved or suffering reduced, not by emotional proximity.',
    source: 'The Life You Can Save — Random House (2009)',
    sourceYear: 2009,
  },
  {
    id: 'kb-13',
    pillar: 'community',
    expert: 'AKDN / Aga Khan Trust for Culture',
    domain: 'Contextual Development',
    directive: 'Localize any capability-transfer initiative to its geographic, cultural, and historical context. Universal solutions applied without local calibration generate dependency, not resilience.',
    source: 'AKDN Ethical Framework — Aga Khan Development Network (2018)',
    sourceYear: 2018,
  },
  {
    id: 'kb-14',
    pillar: 'health',
    expert: 'James Clear',
    domain: 'Habit Architecture',
    directive: 'Stack new micro-behaviors onto existing anchor habits. The cue already exists — you are only adding the routine and reward layers. This reduces activation energy to near zero.',
    source: 'Atomic Habits — Avery Publishing (2018)',
    sourceYear: 2018,
  },
  {
    id: 'kb-15',
    pillar: 'learning',
    expert: 'James Clear',
    domain: 'Marginal Gains',
    directive: 'Pursue 1% compound improvements rather than breakthrough leaps. A 1% daily improvement compounds to 37× better over one year. The system, not the goal, determines the outcome.',
    source: 'Atomic Habits — Avery Publishing (2018)',
    sourceYear: 2018,
  },
]

export const DEFAULT_BASELINES: BaselineItem[] = [
  {
    id: 'bl-1',
    pillar: 'health',
    label: 'Morning light exposure',
    threshold: 'Outdoor light within 60 minutes of waking',
    reflectionPrompt: 'Did you capture morning light with intention, or were you indoors behind glass?',
    logs: [],
  },
  {
    id: 'bl-2',
    pillar: 'health',
    label: 'Consistent sleep anchor',
    threshold: 'Sleep and wake within ±30 min of target times',
    reflectionPrompt: 'Did you honor your sleep window last night, or did you negotiate with it?',
    logs: [],
  },
  {
    id: 'bl-3',
    pillar: 'learning',
    label: 'Deep work block',
    threshold: 'At least one 90-minute uninterrupted focus session',
    reflectionPrompt: 'Was your deep work block genuinely protected, or were you reachable throughout?',
    logs: [],
  },
  {
    id: 'bl-4',
    pillar: 'finance',
    label: 'Automated systems running',
    threshold: 'All scheduled transfers and investments executed without manual intervention',
    reflectionPrompt: 'Did your financial system operate on its own today, or did you intervene unnecessarily?',
    logs: [],
  },
  {
    id: 'bl-5',
    pillar: 'relationships',
    label: 'Positive relational exchange',
    threshold: 'At least one undistracted, engaged interaction with a close person',
    reflectionPrompt: 'Was your presence with someone today full and attentive, or were you physically present but mentally elsewhere?',
    logs: [],
  },
]
